# Generated by Django 2.0.1 on 2018-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductType',
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1),
        ),
    ]
