# Generated by Django 2.0.2 on 2018-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualproduct',
            name='ItemID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='ItemID',
            field=models.TextField(),
        ),
    ]
