# Generated by Django 2.0.2 on 2018-03-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20180308_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='filename',
            field=models.TextField(default='f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manager.Product'),
        ),
    ]
